name: Arduino lint

on:
  push:
#    branches: [ main, dev ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
#  pull_request:
#    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1.0.2
        with:
          # Path containing Arduino projects.
          path: firmware
          # Search path recursively for projects to check.
          recursive: true
          # Show more information on the checks being run.
          verbose: true
