name: X86 TEST - Build DigiLivolo software

on:
  push:
    branches: [ main, dev ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        arch: x86
        packages: |
          build-base
          sudo
          git
          dialog
          python3
          py3-pip
          py3-setuptools
          ninja-build
          samurai
          make
          cmake
          libusb-dev
          eudev
          eudev-libs
          eudev-dev
          curl
          wget
          pkgconf
          pkgconf-dev


    - name: Print OS info
      run: cat /etc/alpine-release; cat /etc/os-release; uname -a; id; sudo id
      shell: alpine.sh {0}

    - name: Install required prerequisite packages on the container and configure git
      run: |
        sudo apk add git dialog python3 py3-pip py3-setuptools ninja-build samurai make cmake libusb-dev eudev eudev-libs eudev-dev curl wget pkgconf-dev pkgconf linux-headers
        git --version
        git config --global --add safe.directory /__w/dl/dl
      shell: alpine.sh {0}

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure CMake project
      run: >
        cmake -B software/build 
        -DCMAKE_BUILD_TYPE=Release
        -DUSE_SYSTEM_HIDAPI=false
        -G Ninja
        -S software
      shell: alpine.sh {0}

    - name: Build software
      run: cmake --build software/build
      shell: alpine.sh {0}

    - name: Print some info on compiled binary
      run: |
        echo "=== objdump -x ==="
        objdump -x software/build/digilivolo || /bin/true
        echo "=== size -A ==="
        size -A software/build/digilivolo || /bin/true
        echo "=== ldd -v ==="
        ldd -v software/build/digilivolo || /bin/true
        echo "=== file & ls ==="
        file software/build/digilivolo || /bin/true
        ls -l software/build/digilivolo || /bin/true
      shell: alpine.sh {0}
