name: X86 TEST - Build DigiLivolo software

on:
  push:
    branches: [ main, dev ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        arch: x86
        packages: |
          build-base
          apt

    - name: Print OS info
      run: cat /etc/alpine-release; cat /etc/os-release; uname -a
      shell: alpine.sh {0}

    - name: Install required prerequisite packages on the container and configure git
      run: |
        apt update
        apt -y full-upgrade
        apt install -y sudo git dialog python3 python3-pip python3-setuptools curl wget || yum install -y sudo git dialog python3 python3-pip python3-setuptools ninja-build make cmake3 libusb-devel libudev-devel curl wget
        git --version
        git config --global --add safe.directory /__w/dl/dl
      shell: alpine.sh {0}
