name: test.yml

on:
  push:
    # branches: [ main ]
    tags:
      - "v*.*.*"
  # pull_request:
    # branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys:
          - { os: windows-latest, shell: 'msys2 {0}' }
          - { os: ubuntu-latest,  shell: bash  }
        compiler:
          - { cc: gcc,   cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: libudev-dev
          
    - name: Debug
      run: |
        ls -l
        pwd
        echo "binary_orig: ${{ matrix.binary_orig }}"
        echo "binary_target: ${{ matrix.binary_target }}"
