name: test.yml

on:
  push:
    # branches: [ main ]
    tags:
      - "vvv*.*.*"
  # pull_request:
    # branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys:
          - { os: windows-latest, shell: 'msys2 {0}' }
          - { os: windows-latest, shell: pwsh }
          - { os: ubuntu-latest,  shell: bash  }
        compiler:
          - { cc: gcc,   cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:

    - name: 'Setup MSYS2'
      if: matrix.sys.shell == 'msys2 {0}'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          git
          make
          mingw-w64-ucrt-x86_64-gcc
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p

    - uses: ConorMacBride/install-package@v1
      with:
        apt: libudev-dev
          
    - name: Debug
      shell: bash
      run: |
        ls -l
        pwd
        echo "matrix.sys.shell: ${{ matrix.sys.shell }}"
        echo "matrix.sys.os: ${{ matrix.sys.os }}"
        gcc --version
